from tkinter import Label, LabelFrame,Button,Tk
root = Tk()
root.geometry("600x400")
root.configure(bg="black")

start_rec= Button(root, text ="Start Recording")
start_rec.grid(row=0,column=0)
stop_rec= Button(root, text ="Stop Recording")
stop_rec.grid(row=0,column=1)
f1 = LabelFrame(root,bg = "black")
f1.pack()
L1= Label(f1,bg = "black")
L1.config(width=80,height=20)
L1.pack()
root.mainloop()
